AWSTemplateFormatVersion: '2010-09-09'
Description: Enable EBS Default Encryption
Resources:
  EbsDefaultEncryption:
    Type: Custom::EbsDefaultEncryption
    Properties:
      KmsKeyId: "aws/ebs"  # defaults to "aws/ebs" if not set
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-ebs-default-encryption-provider'
